version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: cargo
    directory: /anchor_program
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps(rust)"
    groups:
      rust-minor:
        update-types: ["minor", "patch"]
      rust-major:
        update-types: ["major"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps(web)"
    groups:
      web-minor:
        update-types: ["minor", "patch"]
      web-major:
        update-types: ["major"]

  - package-ecosystem: npm
    directory: /anchor_program
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps(anchor-js)"
    groups:
      anchor-js-minor:
        update-types: ["minor", "patch"]
      anchor-js-major:
        update-types: ["major"]
